export enum FavouriteActionTypes {
    FETCH_FAVOURITE = 'FETCH_FAVOURITE',
    FETCH_FAVOURITE_SUCCESS = 'FETCH_FAVOURITE_SUCCESS',
    FETCH_FAVOURITE_ERROR = 'FETCH_FAVOURITE_ERROR',
    UPDATE_FAVOURITE = 'UPDATE_FAVOURITE',
    REMOVE_FAVOURITE = 'REMOVE_FAVOURITE',
}
